#NumPy Exercises
Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.



Import NumPy as np


In [2]:
#Import NumPy as np
import numpy as np

Create an array of 10 zeros


In [3]:

arr_zeros = np.zeros((5,2))

#new_z = np.reshape(arr_zeros,(2,5))
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Create an array of 10 ones


In [4]:
arr_ones = np.ones((5,2))
arr_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Create an array of 10 fives


In [5]:
arr_fives = np.ones(10)*5
arr_fives

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
arr = np.arange(0, 9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
arr2 = np.random.randn(25)
np.reshape(arr2,(5,5))

array([[ 0.29850883,  1.66161677, -0.34301083, -0.17493501, -0.26620009],
       [ 1.90940863,  1.72055025,  1.17635768,  1.24202885, -1.61404738],
       [-1.30129002,  0.51041875, -0.00396625, -0.42225971, -0.3218517 ],
       [ 0.30274564, -1.1102545 ,  1.17258949,  0.46181807, -0.51726243],
       [-0.4756083 ,  1.18922458,  0.31844728,  0.46329444, -2.20195386]])

Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [8]:
arr_random = np.random.randn(25)
arr_random

array([ 1.46230031e+00,  9.25855911e-02,  8.36791266e-01,  1.46466577e-01,
        1.50832337e+00, -1.54691108e+00,  4.96329606e-01, -7.63965851e-01,
       -3.48952308e-01, -4.80084210e-01, -8.93391139e-02, -1.59913739e-01,
        1.30450276e+00, -4.98612696e-02,  2.79197912e+00,  8.12013079e-01,
       -2.59434082e-03,  2.12964349e+00,  5.69869096e-01,  4.96439026e-01,
        1.69632104e+00, -8.00878752e-01, -1.35595374e+00,  1.83822489e-01,
       -2.07478132e-01])

###Numpy Indexing and Selection
Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [10]:
mat = np.arange(1,26).reshape(5,5)
mat


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

#print(mat[2:,1:] )
print(mat[2:5,1:5] )


[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [12]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE
print(mat[3,-1])


20


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE
print(mat[-2:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [13]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE

print(mat[0:3,1])


[ 2  7 12]


In [14]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T BE ABLE TO SEE THE OUTPUT ANY MORE


Get the sum of all the values in mat


In [15]:
print(np.sum(mat))

325


Get the sum of all the columns in mat


In [16]:
print(np.std(mat))

7.211102550927978


Get the standard deviation of the values in mat


In [17]:
print(np.std(mat))

7.211102550927978


#Great Job!
